language: ruby
rvm:
- 2.4

env:
  global:
    secure: TSn7QHR40A2RUSHjs5keR4+NC8a6hgLQDH6IkfFHTLYpXMIHxIliwAP/nE/UtAzLYty57OUuZmTPMW2nBbURGf40rsvktVIhj1idNiEjyk1RuT9NEDcKf2j4eYeQNyhxlJLvHAwEokNFq64kKpf57fokIHkHFdMjDaVgccM9c0baBgvuBHVv+DjNBRngthvp4Zdae3It5JLg5Iz3h4huH40RvI7x8b52DsVhVzWIKNZsQb+46P5IXi0OQEKdIqQacIO3Hx7TMmW49PMIoE0DJcGhzFEeR8SKI3iHEPoqfFO6KNdNHorGFzqPaEVBu5+arCf+2y4BEvw/ocIyTcWzmZShgweqz8tW9R8mn0OF+YU1GklsUUOS95J8FAsuhYwigpcnSu2aWKY/ITFlkGDMegm9GfRDQ0+TRsOM8roZGX6w68eyRv4R9kBDQj0MpvfJ+qs1wJ8s3vZ8WIOIjsrLdKk2Eodt0bPOzPf0gJmIIQJ7a5BLmiMuSwFZYd1lLF057RvcXKtFuHmOAeMZcE90ptzX6D7KTzhmcezXBBncH8Ci0NpSTfNVXyFi7+O7m0bC3RePB1SYoIY0+E53AMfshfbTss3LJZ4cc/NqT3aIT2acSIb2XTipDTFF+hi8AoXp2PBtPa6sIYeRB670ZHO4LExFmA3Xv5Syd4SxlqfKoIA=

deploy:
  provider: script
  on:
    tags: true
    repo: jeefy/vagrant-packet