language: ruby
rvm:
- 2.4
deploy:
  provider: rubygems
  api_key:
    secure: "rf98WBAGC6SYEGm4266mADaP6PqocfjiPfQBMTGuGY0ZkrtV8zyvA1lTtXaxbVtSwopF0ZppGNW/2ArIT6FOlB2gkdL/XOn1d3Ngghkjo/6ozkTyXITrxC0oOzBdLeVtcS/KJXAuC0ZKtXRFRB2cW+PXsaWgbuYOxqCrYCsWFGii7g9mMjgbJZUxuH464gnnIwS4bZjTgzV2ATOVnLT2Hihh31rPDyBcgmNSTVGtrMIFRTDrPpAfZULlG6fD2I+en9Uy/Q5pC107Fo0FVkEl2N28Uu6k9AQCc+jPLubsbccihOUGT3sqwdgNIZADbZrwzvKIIaDkBlKpEKBQH1Wj11fGJ9sxd6wvGIlkDJXY7x5lZ4BnHBiasmesEs3Zi5UOKutHbxtwOTbrbJtA3o9CUTTFUkUGBrH8TFNAtLpDdUGEuTtFpSQAqnuRAz1pCfDgSf25bjGrLZPOiSP9ArE9/x4KXlsuZ/nqwIik8u+y9sjA/JKRy3lQZOo9526Vo7zjm/tc5yT6+LGvJst9qRzIvklhaQMMzVu/QjsDuIrdxLLpqfUyB9OQJwr0vzW/Wr/+yXkkAFBKX675sLtMpZs5BHaRaCi3sUvBLKS4S2oR7UBh6lx+hCQhujrDQwOeGZAQRrP2E6GhovsPmggOh5DJuRW6wLznSyeBWz+c5G4+mHA="
  gem: vagrant-packet
  on:
    tags: true
    repo: jeefy/vagrant-packet
