language: ruby
sudo: false

before_install:
  - gem install bundler
  - gem update bundler

jobs:
  include:
    - stage: gem release
      deploy:
        provider: rubygems
        api_key:
          secure: "PvaqeT7zm7tKHqDN7oZtaroHbRpj1Il9YtnbjfMPmfOKegjAydn34Ny06afUEphdwlReFLOhF3fJI+lhQ1HH887kCKGoekzSoC41yn6CFI52aygnq04aH8pmuOGPJqem5VxjkpMRJdnrQecU76rRRt9uYMXI4qG49u5a6Xjjim0I/9/I79xrWo2nZ8GKc9OlJoi0xDKtjW+p1kii7zpLxOdbYjvbWugJqPUvMItfxBsY3r4pCYcKhekydimybYVN3KpHUSVf/0krAGhZwhYC/RszRDh1MmYnrRVuYKELIDrwBW+ejozlSpPI7dLJCB6FR6v2zeCrV7S+An/FLW/fZKOcTqeVGkhi+mg0/Gpcfxsj6x/4UIwVs6hxchpSXmByxBGa3vjfXx+a8iIYpu1EiZzBFGF07OS1GGndyL2HE8mjanKbcot9K5NW+RzylxXJUwFv3v091/gNdtSIQvcIGlCkDCDZwG5rWekCI0YdNuqfy/IpwpzixuRUFkDWPsc2MzYktm91AHsGXN7JWRGdJWKcQyIXxJ4ths+cq4fxK4U3LJw4OJx7RBOXtxJALH0QaaGLwwdIuklVJQAfv6P6lWVsqebH2e+Q13TlWGK+05XgqEykXKes7Nq8hwBWwkV6182yLquGISnKztMc7o1KMyp3AwWOue6t4Ks5Qc8Cgmk="
        gem: vagrant-packet
        gemspec: vagrant-packet.gemspec
        on:
          tags: true
          branch: master