language: ruby
sudo: false
rvm:
- 2.4
env:
- CI=true
deploy:
  provider: rubygems
  api_key:
    secure: "bsoFk+sF4wTnQjc3WC5NvGws08WMVnLDxxVpoQjhwezQtmWdvAXFLTRMygehUUDuKaPT09VqEQkcsV1hMfTXR2YU8QFNddzECu2f5sNl/vU+QbVGpguG6tiomNbLc0yoyrTtwypEmolPNjeK+bWZhisVfniMaHkAGvx+qr5lhSeSM56S/tIc/A4Sv9soyByx8pFsXt6jKM0WihPUDRy9u5rzi82A8TQKzetkrH7MNQPB6le8C3p5I1BzEd8J7otTG0Mc+C2MvShSBM1qIHyMbZbi5mHN7zOtk2p1MLArmwcKlFGKAHovAC+L5UPwTZrvSmJZppqvNgXFkhSWKC/G5y/hCl7XTW3zy91gxLnlnSa6xeZc8AG1esh04yEw+7/j3cUOr1VspmjrOqM//30pIAvgp66wOmRf49CMNOjD2XPYy64yWvOU3tBYrDdpiZGiQkC87TwxYLYVNskxI2BwrXDAzJgy2T392WSSnwKVDBJYoDchVHDUD06t5eyoSbROJSSZfIB7/sBC2B81rsmqkZ+RnNfLKiUxkARQsB8UYxBVNjUa/ZM9z0/Y/P9btp46VgUPFCJgqdPJvziJ7AhvPW95V+NIcy+ylsxtFX2egg83ltFNkAmm2C1DGK+bLQOBienH2aeYcewakHlaLgcV713J+s+9dV6s5mx20wpaJJE="
  gem: vagrant-packet
  gemspec: vagrant-packet.gemspec
  on:
    tags: true
    repo: jeefy/vagrant-packet
