language: ruby
sudo: false

before_install:
  - gem install bundler
  - gem update bundler

jobs:
  include:
    - stage: gem release
      deploy:
        provider: rubygems
        api_key:
          secure: "R873GclxxHZNvjcvDVvJ3TI6mVNLj1eJsZsTz+HSvlbq7w3v5cMtvWStSKgXPUqaVcJdq6HACn++GOL0PAhj7AAnDHZd2I9q2OJEwmCx+ylCPh17SmhEHOTE5CK9SqEoqlKrJhsnDNR+KIg0dq42dNIm/iYOIMmNUtB1wCqkDii/w0SBTKejrMYg7P2UGNUolInmXqj6QKAZ96K4IVXGKMM8oUS1fnsnP0viEp1h8INonHWqN7Q3FLLx8mZ2J3dUPCZ2x0xCal2XCJ/DbYyH88HcBMl8DF4N4LS8GlG3L7eA9s5aCFlWllH+sEbd8UozAlD+3mULodbCEkVlKYOwepf+z560plW0s1rhyp5khVqBWJzfm+q+vcIoslLDJr7oiWNa03bE6W/TUcFe2tIC2SPe+R0aKpsqYH9Qkt0QMoHbvXTPuIYjP4M8U0MYxrvzgHZz5g71U9AFIP6IoHx2Dgq1FK4a5blYOU3+/xbE5dPQSVijEgj+0MbfYziP89PoLfnHiah088Kj4u8dRjkzxa2M/FZEDB97Lvtctwk79VSUVb9f2AP0znMRAu5Lac5yAJKmlzqBxMMKzr+ybMvBmDeJ02SNpl3kylwqyZ9+shOgWVzWINiMjj/D4qvDe0ILu+QkwMg+2muApBY1U6XInTOOb8AHajkBL7g61iFzvlE="
        gem: vagrant-packet
        gemspec: vagrant-packet.gemspec
        on:
          tags: true
          branch: master