language: ruby
sudo: false
rvm:
- 2.4
env:
- CI=true
deploy:
  provider: rubygems
  api_key:
    secure: "lPT6AYj7mr/8cFtsssMGcce7mS+nSVrKHCWaQtCRpT4/Rt+Bvhs8GsA2XkjxusVo0JUjtqSp252w3+P5XDdkuElTjqFxHdDElUiDYFkGLR61bBTReXnE5RVdLIHX1nS//jaFSYhB7uxbSnodA1a9J+koeb0NUK4WBwO9CeC0+SS9Ic3gw9VYagLEd+lqHNryUw/n8pYSeU+Al6PyJOs4r7R+69zxDL7JBr37KQITA6z5ZtrDqOdVluJhpGzBFKVCmjuC9b321ox7KcY6epCMApUUm6wFCXtRJZEDe2+bnbJzQ1Vk6EgdrRP/sdskvdcR6jhzEr4qi/biAC4lAzQVxHX1cxSznihMbdsJ8tSphGLm7fNEQyUrtmFOGyCMVMBpQb/aFTfNtoqCeCcNCf5apmrfvsw73Tg8Yihzfz5xTZkWJl4Q0VdmjcZPQ3wuV6qoWnRCQ/vFbfpyg4kjZ1miIs5fTj7ZyhDPXIAJKA67fwg6Brpic2dgDOVVoqiCDTEURix25KjjjVxgBkMxtWhVxa6PYXrPhz8TBr6apdgsKHwJM54c4TdWk4ugToGGgAY+G+DeK6TYLlZWtT+Z44MxMyHEd4P/VJ6AclP7we56p2KZGug1luozzWfKFUOGUdMtIIUiqfJA/Yn+k/T9iNFE3VpH67bczMYaOndYGzTG/+w="
  gem: vagrant-packet
  gemspec: vagrant-packet.gemspec
  on:
    tags: true
    repo: jeefy/vagrant-packet
